services:
  - type: web
    name: heart-failure-backend
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn heart_failure_prediction.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: heart_failure_prediction.settings
      - key: SECRET_KEY
        fromDatabase: true
      - key: DEBUG
        value: 'False'
    autoDeploy: true
