services:
  - type: web
    name: heart-failure-prediction
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn heart_failure_prediction.heart_failure_prediction.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: heart_failure_prediction.settings
      - key: SECRET_KEY
        fromDatabase: true
      - key: DEBUG
        value: 'False'
    workingDirectory: ./       # <--- Make sure to add this line pointing to root
    autoDeploy: true
